# Generated by Django 3.0.11 on 2021-01-18 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, unique=True)),
                ('lft', models.PositiveIntegerField()),
                ('rgt', models.PositiveIntegerField()),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.Category')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
